
$(function() {

    // JS Objects for random generator

    WTF.init({

        heading: [
        "Thats what she said!",
        "Thats what he said!",
        "Once upon a time in wdi12",
        "dat day in hipsterland",
        "Standup time!",
        ],
        response: [
        "yeh bro i know it was",
        "right in dem feelz",
        "nostalgia hits again",
        "Thanks for the mems bro",
        "Im gonna miss it",
        "Im crying under my snapback",
        ],
        template: [
        "Was it @name who said? @phrase",
        "Did @name mention this: @phrase",
        ],
        name: [
        "Gerry",
        "Alex",
        "Elena",
        "Filippo",
        "Cheryl",
        "Spencer",
        "James",
        "Christabel",
        "Dani",
        "Jon (Snow)",
        "Erica",
        "Hassan",
        "Rane",
        "Tyroneeeee"
        ],
        phrase: [
        "The board is over here!",
        "I stayed up until 4am trying to fix a bug",
        "couldn't sleep, went for a run at 3am",
        "i swear center align wasnt working for me last night",
        "sorry im having sorry my breakfast sorry",
        "Fantastich",
        "Suns out leg guns out - that phrase...",
        "Schwing",
        "BOOM!",
        "Zing!",
        "Whaaaaat?",
        "Thats interesting...",
        "Cheeky Banter",
        "BANTEEEEEERRRR",
        "That wasnt porn... someone sent me a football video",
        "I have an error!",
        "he put the midget in the closet to show his friends",
        "i have a question. ah nevermind",
        "bantasaurus rex",
        "is this bonus for free nandos?",
        "(snaps fingers in glee)",
        "fist to five?",
        "(singing) When a man loves a woman...",
        "Hassan... that was the other classes TA (with a beard)",
        "two words = much coding!",
        "big chill? big chill!",
        "meeting? meeting.",
        "mandatory homework: go to the pub!",
        "did i win the pint? wait i dont drink",
        "im not going to shave until the end of the course",
        "mta subway... death to ruby",
        "alright, its basically like this...",
        "do you get the ID(ea)?",
        "Gerry the project is up here!",
        "When in doubt: pizza!",
        "What the fuck is gerry doing here",
        "/giphy ****",
        "you are ninjas",
        "how is everyone doing?",
        "i just realised your surname was gotsell: one word. i thought it was a rap phrase i hadn't heard of yet",
        "im hungry",
        "no homework? =D",
        "rane? rain?",
        "I hate CSS!",
        "CSS is my friend - it has no errors",
        "who invented rugby?",
        "duck debugging - never to be seen again",
        "lets talk about the queen",
        "im lost",
        "brain explosion",
        "yes gerry! thats amazing gerry!",
        "did u submit ur homework? do a PR!",
        "at least im hanging from a strawberry tree",
        "at least im hanging from a strawberry tree",
        "at least im hanging from a strawberry tree",
        "he grounded a plane after using the lavatory",
        "Mac Classic!",
        "Gerry and James - modern love story",
        "Did u get the Amazon confirmation code, no? go outside then.",
        "note to james: Frustrated man charged by police after shooting his uncooperative computer",
        "awesome nickname! not that awesome, awesome would be like @gerronosauras-rex",
        "bundleeeeeee!",
        ]
    });
});